import type { Metadata } from 'next';
import fs from 'node:fs';
import path from 'node:path';

import { CallToAction } from '@/components/molecules/CallToAction';
import { Hero } from '@/components/molecules/Hero';
import { RegistryTable, type RegistryTableRow } from '@/components/molecules/RegistryTable';
import { buildMetadata } from '@/lib/seo';

export const metadata: Metadata = buildMetadata({
  section: 'builder',
  description:
    'The full ADR registry — every architecture decision recorded, dated, and tagged. Auto-built from docs/architecture/adrs by scripts/ops/build_adr_registry.py.',
  path: '/builders/adrs',
});

type AdrRegistryEntry = {
  number: number;
  slug: string;
  title: string;
  status: string;
  date: string;
  tags: string[];
  deciders: string[];
  source_path: string;
};

type AdrRegistry = {
  schema_version: number;
  generated_at: string;
  source_dir: string;
  stale: boolean;
  parse_errors: string[];
  adrs: AdrRegistryEntry[];
};

const REGISTRY_PATH = path.join(process.cwd(), 'public', 'adrs', 'registry.json');

function loadRegistry(): AdrRegistry {
  try {
    const raw = fs.readFileSync(REGISTRY_PATH, 'utf-8');
    return JSON.parse(raw) as AdrRegistry;
  } catch {
    return {
      schema_version: 1,
      generated_at: '',
      source_dir: 'docs/architecture/adrs',
      stale: true,
      parse_errors: ['registry not yet built — run scripts/ops/build_adr_registry.py'],
      adrs: [],
    };
  }
}

function adrToRow(entry: AdrRegistryEntry): RegistryTableRow {
  const githubHref = `https://github.com/Azure-Samples/holiday-peak-hub/blob/main/${entry.source_path}`;
  return {
    key: `adr-${entry.number}`,
    cells: [
      { kind: 'text', value: `ADR-${String(entry.number).padStart(3, '0')}` },
      { kind: 'link', value: entry.title, href: githubHref },
      { kind: 'badge', value: entry.status },
      { kind: 'text', value: entry.date },
      { kind: 'tags', values: entry.tags.length > 0 ? entry.tags : ['—'] },
    ],
  };
}

/**
 * `/builders/adrs` — auto-generated ADR registry (Issue #1048 / Epic #1053).
 *
 * Read at build time from `apps/ui/public/adrs/registry.json`, which is
 * generated by `scripts/ops/build_adr_registry.py` and refreshed on every
 * SWA build.
 *
 * If the registry is stale (parse errors), a warning banner renders above
 * the table; the table still renders all successfully-parsed ADRs. This
 * matches Epic #1053's "default produces empty-but-valid JSON with stale
 * banner" rule.
 */
export default function BuilderAdrsPage() {
  const registry = loadRegistry();
  const rows = registry.adrs
    .slice()
    .sort((a, b) => a.number - b.number)
    .map(adrToRow);

  return (
    <>
      <Hero
        kind="audience-page"
        headline="The ADR registry."
        sub={`${registry.adrs.length} architecture decisions on the record. Every entry is auto-extracted from docs/architecture/adrs.`}
        primaryCta={{ label: 'See architecture diagrams', href: '/builders/architecture' }}
        secondaryCta={{ label: 'Browse pattern catalog', href: '/builders/patterns' }}
        testId="builder-adrs-hero"
      />
      <RegistryTable
        testId="builder-adrs-table"
        headline="Architecture Decision Records"
        description="Auto-built by scripts/ops/build_adr_registry.py from front-matter inside each ADR file. Source dir: docs/architecture/adrs."
        columns={['ID', 'Title', 'Status', 'Date', 'Tags']}
        rows={rows}
        banner={
          registry.stale
            ? {
                tone: 'warn',
                text: `Registry stale — ${registry.parse_errors.length} parse warning(s). Run scripts/ops/build_adr_registry.py --strict locally to see details.`,
              }
            : registry.generated_at
              ? {
                  tone: 'info',
                  text: `Last generated ${registry.generated_at}.`,
                }
              : undefined
        }
        emptyState={{
          headline: 'No ADRs in the registry yet.',
          body: 'Run scripts/ops/build_adr_registry.py to generate the registry from docs/architecture/adrs.',
        }}
      />
      <CallToAction
        tone="audience-pair"
        headline="Looking at the wider system?"
        primary={{ label: 'See architecture diagrams', href: '/builders/architecture' }}
        secondary={{ label: 'Browse pattern catalog', href: '/builders/patterns' }}
        testId="builder-adrs-cta-pair"
      />
    </>
  );
}
