"""Connector contracts and registry exports."""

from holiday_peak_lib.connectors.protocols import (
    AnalyticsConnectorBase,
    AnalyticsConnectorProtocol,
    AssetData,
    CRMConnectorBase,
    CRMConnectorProtocol,
    CommerceConnectorBase,
    CommerceConnectorProtocol,
    CustomerData,
    DAMConnectorBase,
    DAMConnectorProtocol,
    IdentityConnectorBase,
    IdentityConnectorProtocol,
    IntegrationConnectorBase,
    IntegrationConnectorProtocol,
    InventoryConnectorBase,
    InventoryConnectorProtocol,
    InventoryData,
    OrderData,
    PIMConnectorBase,
    PIMConnectorProtocol,
    ProductData,
    SegmentData,
    WorkforceConnectorBase,
    WorkforceConnectorProtocol,
)
from holiday_peak_lib.connectors.registry import ConnectorRegistration, ConnectorRegistry

__all__ = [
    "AssetData",
    "ProductData",
    "InventoryData",
    "CustomerData",
    "OrderData",
    "SegmentData",
    "PIMConnectorBase",
    "DAMConnectorBase",
    "InventoryConnectorBase",
    "CRMConnectorBase",
    "CommerceConnectorBase",
    "AnalyticsConnectorBase",
    "IntegrationConnectorBase",
    "IdentityConnectorBase",
    "WorkforceConnectorBase",
    "PIMConnectorProtocol",
    "DAMConnectorProtocol",
    "InventoryConnectorProtocol",
    "CRMConnectorProtocol",
    "CommerceConnectorProtocol",
    "AnalyticsConnectorProtocol",
    "IntegrationConnectorProtocol",
    "IdentityConnectorProtocol",
    "WorkforceConnectorProtocol",
    "ConnectorRegistration",
    "ConnectorRegistry",
]
